"""
This type stub file was generated by pyright.
"""

"""
    pyudev._os
    ==========

    Extras to compensate for deficiencies in python os module.

    .. moduleauthor::  mulhern  <amulhern@redhat.com>
"""
