"""
This type stub file was generated by pyright.
"""

from ._device import Attributes as Attributes
from ._device import Device as Device
from ._device import Devices as Devices
from ._device import Tags as Tags

"""
    pyudev.device
    =============

    Device class implementation of :mod:`pyudev`.

    .. moduleauthor::  Sebastian Wiesner  <lunaryorn@gmail.com>
"""
